#!/usr/bin/env pwsh
#
# Generic script to generate WiX fragment files for backend dependency files
# Scans a backend directory recursively and generates WiX XML components for all files
# except the specified exclusion file (typically ggml-*.dll runtime file).
#
# This script is backend-agnostic and derives all configuration from parameters.
#

param(
    [Parameter(Mandatory=$true)]
    [string]$BackendPath,

    [Parameter(Mandatory=$true)]
    [string]$ComponentGroupId,

    [Parameter(Mandatory=$true)]
    [string]$RootDirectoryId,

    [Parameter(Mandatory=$true)]
    [string]$DistDir,

    [Parameter(Mandatory=$true)]
    [string]$OutputFile,

    [Parameter(Mandatory=$false)]
    [string]$ExcludeFile = "",

    [Parameter(Mandatory=$false)]
    [string]$Arch = "amd64",

    [Parameter(Mandatory=$false)]
    [switch]$NoRecurse
)

$ErrorActionPreference = "Stop"

$fullBackendPath = Join-Path $DistDir "windows-$Arch\$BackendPath"
# Resolve to absolute path for proper substring calculations later
$fullBackendPath = (Resolve-Path $fullBackendPath -ErrorAction SilentlyContinue).Path
if (-Not $fullBackendPath) {
    # Path doesn't exist yet, construct absolute path manually
    $fullBackendPath = [System.IO.Path]::GetFullPath((Join-Path $DistDir "windows-$Arch\$BackendPath"))
}

Write-Host "Scanning for dependency files in: $fullBackendPath"
if ($ExcludeFile) {
    Write-Host "Excluding file: $ExcludeFile"
}

if (-Not (Test-Path $fullBackendPath)) {
    Write-Host "WARNING: Backend directory not found: $fullBackendPath"
    Write-Host "Creating empty component group"

    $xmlContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY -->
<!-- Generated by generate-backend-deps.ps1 -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="$ComponentGroupId" Directory="$RootDirectoryId">
      <!-- No files found during build -->
    </ComponentGroup>
  </Fragment>
</Wix>
"@

    $xmlContent | Out-File -FilePath $OutputFile -Encoding UTF8
    Write-Host "Created empty fragment: $OutputFile"
    exit 0
}

# Find all files, excluding the specified file(s).
# ExcludeFile can be a single filename or comma-separated list with wildcards
# (e.g., "mlx.dll,mlxc.dll" or "ggml-cpu*.dll").
$getChildItemArgs = @{
    Path = $fullBackendPath
    File = $true
}
if (-not $NoRecurse) {
    $getChildItemArgs.Recurse = $true
}
$allFiles = Get-ChildItem @getChildItemArgs | Sort-Object FullName
if ($ExcludeFile) {
    $excludeList = $ExcludeFile -split ',' | ForEach-Object { $_.Trim() }
    $depFiles = $allFiles | Where-Object {
        $fileName = $_.Name
        -not ($excludeList | Where-Object { $fileName -like $_ })
    }
} else {
    $depFiles = $allFiles
}

Write-Host "Found $($depFiles.Count) dependency file(s):"
foreach ($file in $depFiles) {
    $relativePath = $file.FullName.Substring($fullBackendPath.Length + 1)
    Write-Host "  - $relativePath"
}

if ($depFiles.Count -eq 0) {
    Write-Host "WARNING: No dependency files found"
    Write-Host "Creating empty component group"

    $xmlContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY -->
<!-- Generated by generate-backend-deps.ps1 -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="$ComponentGroupId" Directory="$RootDirectoryId">
      <!-- No dependency files found during build -->
    </ComponentGroup>
  </Fragment>
</Wix>
"@

    $xmlContent | Out-File -FilePath $OutputFile -Encoding UTF8
    Write-Host "Created empty fragment: $OutputFile"
    exit 0
}

function Get-StableHash {
    param(
        [Parameter(Mandatory=$true)]
        [string]$InputString,

        [Parameter(Mandatory=$false)]
        [int]$Length = 12
    )

    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hashBytes = $sha256.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($InputString))
        $hash = -join ($hashBytes | ForEach-Object { $_.ToString("x2") })
        return $hash.Substring(0, [Math]::Min($Length, $hash.Length))
    } finally {
        $sha256.Dispose()
    }
}

function ConvertTo-WixIdentifier {
    param(
        [Parameter(Mandatory=$true)]
        [string]$InputString
    )

    $maxIdentifierLength = 72
    $safeIdentifier = $InputString -replace '[\\/]', '_' -replace '[^a-zA-Z0-9_]', '_'

    if ($safeIdentifier.Length -le $maxIdentifierLength) {
        return $safeIdentifier
    }

    $hashSuffix = "_" + (Get-StableHash -InputString $safeIdentifier)
    $prefixLength = $maxIdentifierLength - $hashSuffix.Length
    return $safeIdentifier.Substring(0, $prefixLength).TrimEnd('_') + $hashSuffix
}

function Get-DirectoryId {
    param(
        [Parameter(Mandatory=$false)]
        [AllowEmptyString()]
        [string]$DirPath
    )

    if ([string]::IsNullOrEmpty($DirPath)) {
        return $RootDirectoryId
    }

    $leafName = [System.IO.Path]::GetFileName($DirPath)
    if ([string]::IsNullOrEmpty($leafName)) {
        $leafName = "Dir"
    }
    $leafName = $leafName -replace '[^a-zA-Z0-9_]', '_'
    $pathHash = Get-StableHash -InputString $DirPath

    return ConvertTo-WixIdentifier -InputString "${RootDirectoryId}_${leafName}_${pathHash}"
}

# Collect all unique subdirectories and their parent directories
$subdirectories = @{}
foreach ($file in $depFiles) {
    $relativePath = $file.FullName.Substring($fullBackendPath.Length + 1)
    $dirPath = [System.IO.Path]::GetDirectoryName($relativePath)

    # Add this directory and all parent directories
    while ($dirPath) {
        if (-not $subdirectories.ContainsKey($dirPath)) {
            $subdirectories[$dirPath] = $true
        }
        $dirPath = [System.IO.Path]::GetDirectoryName($dirPath)
    }
}

# Generate WiX XML
$xmlBuilder = New-Object System.Text.StringBuilder
[void]$xmlBuilder.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
[void]$xmlBuilder.AppendLine('<!-- AUTO-GENERATED FILE - DO NOT EDIT MANUALLY -->')
[void]$xmlBuilder.AppendLine('<!-- Generated by generate-backend-deps.ps1 -->')
[void]$xmlBuilder.AppendLine('<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">')
[void]$xmlBuilder.AppendLine('  <Fragment>')

# Generate directory structure for subdirectories
if ($subdirectories.Count -gt 0) {
    [void]$xmlBuilder.AppendLine("    <!-- Directory structure -->")

    # Generate DirectoryRef for each unique subdirectory path
    foreach ($dirPath in ($subdirectories.Keys | Sort-Object)) {
        $parentDirId = $RootDirectoryId

        # If this is a nested path, determine the parent directory ID
        $parentPath = [System.IO.Path]::GetDirectoryName($dirPath)
        if ($parentPath) {
            $parentDirId = Get-DirectoryId -DirPath $parentPath
        }

        $dirName = [System.IO.Path]::GetFileName($dirPath)
        $fullDirId = Get-DirectoryId -DirPath $dirPath

        [void]$xmlBuilder.AppendLine("    <DirectoryRef Id=`"$parentDirId`">")
        [void]$xmlBuilder.AppendLine("      <Directory Id=`"$fullDirId`" Name=`"$dirName`" />")
        [void]$xmlBuilder.AppendLine("    </DirectoryRef>")
    }
    [void]$xmlBuilder.AppendLine("")
}

# Group files by directory
$filesByDir = @{}
foreach ($file in $depFiles) {
    $relativePath = $file.FullName.Substring($fullBackendPath.Length + 1)
    $dirPath = [System.IO.Path]::GetDirectoryName($relativePath)
    if (-not $dirPath) { $dirPath = "" }

    if (-not $filesByDir.ContainsKey($dirPath)) {
        $filesByDir[$dirPath] = @()
    }
    $filesByDir[$dirPath] += $file
}

# Function to generate a stable GUID based on a string
function Get-StableGuid {
    param([string]$InputString)

    $md5 = [System.Security.Cryptography.MD5]::Create()
    $hash = $md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($InputString))

    # Convert hash to GUID format
    return [System.Guid]::new($hash).ToString("B").ToUpper()
}

# Generate component group
[void]$xmlBuilder.AppendLine("    <ComponentGroup Id=`"$ComponentGroupId`" Directory=`"$RootDirectoryId`">")

# Root directory files (no subdirectory)
if ($filesByDir.ContainsKey("")) {
    foreach ($file in $filesByDir[""]) {
        $sourcePath = "$BackendPath\$($file.Name)"
        [void]$xmlBuilder.AppendLine("      <Component><File Source=`"$sourcePath`"/></Component>")
    }
}

# Subdirectory files - group all files in the same subdirectory into a single component
foreach ($dirPath in ($filesByDir.Keys | Where-Object { $_ -ne "" } | Sort-Object)) {
    $files = $filesByDir[$dirPath]

    # Generate directory ID for this subdirectory
    $dirId = Get-DirectoryId -DirPath $dirPath

    # Generate a stable GUID based on the component group ID and directory path
    $componentGuid = Get-StableGuid "$ComponentGroupId-$dirPath"

    [void]$xmlBuilder.AppendLine("      <!-- Files in $dirPath -->")
    [void]$xmlBuilder.AppendLine("      <Component Directory=`"$dirId`" Guid=`"$componentGuid`">")

    foreach ($file in $files) {
        $relativePath = $file.FullName.Substring($fullBackendPath.Length + 1)
        $sourcePath = "$BackendPath\$relativePath" -replace '/', '\'
        [void]$xmlBuilder.AppendLine("        <File Source=`"$sourcePath`"/>")
    }

    [void]$xmlBuilder.AppendLine('      </Component>')
}

[void]$xmlBuilder.AppendLine('    </ComponentGroup>')
[void]$xmlBuilder.AppendLine('  </Fragment>')
[void]$xmlBuilder.AppendLine('</Wix>')

# Write to output file
$xmlBuilder.ToString() | Out-File -FilePath $OutputFile -Encoding UTF8

Write-Host "Generated WiX fragment: $OutputFile"
Write-Host "Component group: $ComponentGroupId"
Write-Host "Total components: $(($filesByDir.Keys | Measure-Object).Count)"
