version: "2"
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - gocheckcompilerdirectives
    - intrange
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - unconvert
    - usetesting
    - wastedassign
    - whitespace
  disable:
    - errcheck
    - usestdlibvars
  settings:
    govet:
      disable:
        - unusedresult
    staticcheck:
      checks:
        - all
        - -QF* # disable quick fix suggestions
        - -SA1019
        - -ST1000 # package comment format
        - -ST1003 # underscores in package names
        - -ST1005 # error strings should not be capitalized
        - -ST1012 # error var naming (ErrFoo)
        - -ST1016 # receiver name consistency
        - -ST1020 # comment on exported function format
        - -ST1021 # comment on exported type format
        - -ST1022 # comment on exported var format
        - -ST1023 # omit type from declaration
severity:
  default: error
  rules:
    - linters:
        - gofmt
        - goimports
        - intrange
      severity: info
formatters:
  enable:
    - gofmt
    - gofumpt
