run:
  timeout: 5m
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - errcheck
    - exportloopref
    - gci
    - gocheckcompilerdirectives
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
linters-settings:
  gci:
    sections: [standard, default, localmodule]
  staticcheck:
    checks:
      - all
      - -SA1019 # omit Deprecated check
severity:
  default-severity: error
  rules:
    - linters:
        - gofmt
        - goimports
        - intrange
        - usestdlibvars
      severity: info
