version: "2"
linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - errcheck
    - errorlint
    - exptostd
    - gocheckcompilerdirectives
    - gocritic
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - modernize
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - sloglint
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
    gocritic:
      disabled-checks:
        # Detects suspicious duplicated sub-expressions.
        # Prone to false positives when used on cgo code
        # https://github.com/go-critic/go-critic/issues/897#issuecomment-568892104
        - dupSubExpr
    perfsprint:
      strconcat: false
      concat-loop: false
    staticcheck:
      checks:
        - all
        # Using a deprecated function, variable, constant or field.
        # https://staticcheck.dev/docs/checks/#SA1019
        - -SA1019
        # Poorly chosen identifier.
        # https://staticcheck.dev/docs/checks/#ST1003
        - -ST1003
    usestdlibvars:
      http-method: false
      http-status-code: false
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - prealloc

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
