#!/bin/bash
#
# github-api-helper.sh - Helper script for GitHub API operations
# 
# Usage: ./github-api-helper.sh [command] [args...]
# 
# Commands:
#   setup                          - Interactive setup of GitHub credentials
#   status                         - Check GitHub API status and rate limits
#   update-issue <num> <state>     - Update issue state (open/closed)
#   label <num> <labels...>        - Add labels to issue
#   comment <num> "comment text"   - Add comment to issue
#   list-issues <filter>           - List issues (optional: label, state)
#   verify                         - Verify token is valid
# 
# Examples:
#   ./github-api-helper.sh setup
#   ./github-api-helper.sh status
#   ./github-api-helper.sh update-issue 1234 closed
#   ./github-api-helper.sh label 1234 bug critical
#   ./github-api-helper.sh comment 1234 "Fixed in v0.2.0"
#

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Load environment from .env if it exists
if [ -f .env ]; then
    export $(cat .env | grep -v '^#' | xargs)
fi

# Check if required variables are set
check_config() {
    if [ -z "$GITHUB_TOKEN" ]; then
        echo -e "${RED}✗ GITHUB_TOKEN not set${NC}"
        echo "Run: ./github-api-helper.sh setup"
        return 1
    fi
    if [ -z "$GITHUB_USER" ]; then
        GITHUB_USER="kushin77"
    fi
    if [ -z "$GITHUB_REPO" ]; then
        GITHUB_REPO="ollama"
    fi
    return 0
}

# Setup credentials interactively
setup_credentials() {
    echo -e "${BLUE}🔧 GitHub API Setup${NC}"
    echo ""
    
    # Ask for token
    echo "1. Get your GitHub Personal Access Token:"
    echo "   - Go to: https://github.com/settings/tokens"
    echo "   - Click: Generate new token (classic)"
    echo "   - Select scopes: repo, write:repo_hook, admin:repo_hook, workflow"
    echo ""
    read -p "Enter your GitHub token (ghp_...): " token
    
    if [ -z "$token" ]; then
        echo -e "${RED}✗ Token is required${NC}"
        return 1
    fi
    
    # Ask for username
    echo ""
    read -p "Enter GitHub username [kushin77]: " user
    user=${user:-kushin77}
    
    # Ask for repo
    echo ""
    read -p "Enter repository name [ollama]: " repo
    repo=${repo:-ollama}
    
    # Create .env file
    cat > .env << EOF
# GitHub API Integration - Auto-generated by github-api-helper.sh
GITHUB_TOKEN=$token
GITHUB_USER=$user
GITHUB_REPO=$repo
EOF
    
    echo ""
    echo -e "${GREEN}✓ Configuration saved to .env${NC}"
    echo "  - GITHUB_USER: $user"
    echo "  - GITHUB_REPO: $repo"
    echo ""
    echo -e "${YELLOW}⚠️  WARNING: .env file contains sensitive data!${NC}"
    echo "  - Make sure .env is in .gitignore"
    echo "  - Never commit .env to version control"
    echo ""
    
    # Verify token
    verify_token
}

# Verify token is valid
verify_token() {
    if ! check_config; then
        return 1
    fi
    
    echo -e "${BLUE}🔍 Verifying token...${NC}"
    
    response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        https://api.github.com/user)
    
    if echo "$response" | grep -q "login"; then
        username=$(echo "$response" | grep '"login"' | head -1 | cut -d'"' -f4)
        echo -e "${GREEN}✓ Token is valid!${NC}"
        echo "  Authenticated as: $username"
        return 0
    else
        echo -e "${RED}✗ Token verification failed${NC}"
        if echo "$response" | grep -q "Bad credentials"; then
            echo "  Error: Bad credentials - token may be expired or invalid"
        fi
        echo "  Response: $response"
        return 1
    fi
}

# Check GitHub API status and rate limits
check_status() {
    if ! check_config; then
        return 1
    fi
    
    echo -e "${BLUE}📊 GitHub API Status${NC}"
    echo ""
    
    response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        https://api.github.com/rate_limit)
    
    if echo "$response" | grep -q "remaining"; then
        limit=$(echo "$response" | grep -o '"limit": [0-9]*' | head -1 | grep -o '[0-9]*')
        remaining=$(echo "$response" | grep -o '"remaining": [0-9]*' | head -1 | grep -o '[0-9]*')
        reset=$(echo "$response" | grep -o '"reset": [0-9]*' | head -1 | grep -o '[0-9]*')
        
        # Convert reset time
        reset_time=$(date -d @"$reset" 2>/dev/null || date -r "$reset" 2>/dev/null || echo "unknown")
        
        echo -e "  ${GREEN}Limit:${NC}     $limit requests"
        echo -e "  ${GREEN}Remaining:${NC} $remaining requests"
        echo -e "  ${GREEN}Reset at:${NC}  $reset_time"
        echo ""
        
        # Warn if running low
        if [ "$remaining" -lt 100 ]; then
            echo -e "${YELLOW}⚠️  WARNING: Running low on API requests!${NC}"
            percent=$((remaining * 100 / limit))
            echo "  Only $percent% of quota remaining"
        fi
    else
        echo -e "${RED}✗ Failed to retrieve rate limit info${NC}"
        return 1
    fi
}

# Update issue state
update_issue() {
    local issue_num=$1
    local state=$2
    
    if ! check_config; then
        return 1
    fi
    
    if [ -z "$issue_num" ] || [ -z "$state" ]; then
        echo -e "${RED}✗ Usage: $0 update-issue <issue_number> <state>${NC}"
        echo "  state: open or closed"
        return 1
    fi
    
    if [ "$state" != "open" ] && [ "$state" != "closed" ]; then
        echo -e "${RED}✗ Invalid state: $state (must be 'open' or 'closed')${NC}"
        return 1
    fi
    
    echo -e "${BLUE}Updating issue #$issue_num to state: $state${NC}"
    
    response=$(curl -s -X PATCH \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/issues/$issue_num \
        -d "{\"state\":\"$state\"}")
    
    if echo "$response" | grep -q '"state"'; then
        echo -e "${GREEN}✓ Issue #$issue_num updated to: $state${NC}"
        return 0
    else
        echo -e "${RED}✗ Failed to update issue${NC}"
        echo "  Response: $response"
        return 1
    fi
}

# Add labels to issue
add_labels() {
    local issue_num=$1
    shift
    local labels="$@"
    
    if ! check_config; then
        return 1
    fi
    
    if [ -z "$issue_num" ] || [ -z "$labels" ]; then
        echo -e "${RED}✗ Usage: $0 label <issue_number> <label1> <label2>...${NC}"
        return 1
    fi
    
    # Convert labels to JSON array
    label_json=$(echo "$labels" | sed 's/ /", "/g' | sed 's/^/["/;s/$/"]/')
    
    echo -e "${BLUE}Adding labels to issue #$issue_num: $labels${NC}"
    
    response=$(curl -s -X PATCH \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/issues/$issue_num \
        -d "{\"labels\":$label_json}")
    
    if echo "$response" | grep -q '"labels"'; then
        echo -e "${GREEN}✓ Labels added to issue #$issue_num${NC}"
        return 0
    else
        echo -e "${RED}✗ Failed to add labels${NC}"
        echo "  Response: $response"
        return 1
    fi
}

# Add comment to issue
add_comment() {
    local issue_num=$1
    local comment=$2
    
    if ! check_config; then
        return 1
    fi
    
    if [ -z "$issue_num" ] || [ -z "$comment" ]; then
        echo -e "${RED}✗ Usage: $0 comment <issue_number> \"comment text\"${NC}"
        return 1
    fi
    
    echo -e "${BLUE}Adding comment to issue #$issue_num${NC}"
    
    # Escape comment for JSON
    comment_json=$(echo "$comment" | sed 's/"/\\"/g')
    
    response=$(curl -s -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/issues/$issue_num/comments \
        -d "{\"body\":\"$comment_json\"}")
    
    if echo "$response" | grep -q '"id"'; then
        echo -e "${GREEN}✓ Comment added to issue #$issue_num${NC}"
        return 0
    else
        echo -e "${RED}✗ Failed to add comment${NC}"
        echo "  Response: $response"
        return 1
    fi
}

# List issues
list_issues() {
    local filter=$1
    
    if ! check_config; then
        return 1
    fi
    
    echo -e "${BLUE}📝 Listing issues (filter: ${filter:-none})${NC}"
    echo ""
    
    # Build query
    query="https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/issues?state=open&per_page=10"
    if [ -n "$filter" ]; then
        query="$query&labels=$filter"
    fi
    
    response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$query")
    
    # Parse and display
    echo "$response" | grep -o '"number": [0-9]*\|"title": "[^"]*"\|"labels"' | paste - - - | \
        awk -F: '{
            if (NR % 3 == 1) printf "  #"; 
            if (NR % 3 == 1) print $2 " " $4; 
        }' | head -10
    
    echo ""
}

# Main command dispatcher
main() {
    local cmd=$1
    shift || true
    
    case "$cmd" in
        setup)
            setup_credentials
            ;;
        status)
            check_status
            ;;
        verify)
            verify_token
            ;;
        update-issue)
            update_issue "$@"
            ;;
        label)
            add_labels "$@"
            ;;
        comment)
            add_comment "$@"
            ;;
        list-issues)
            list_issues "$@"
            ;;
        "")
            echo -e "${BLUE}📋 GitHub API Helper${NC}"
            echo ""
            echo "Usage: ./github-api-helper.sh [command] [args...]"
            echo ""
            echo "Commands:"
            echo "  setup                    - Interactive setup"
            echo "  status                   - Check API status and rate limits"
            echo "  verify                   - Verify token is valid"
            echo "  update-issue <num> <state> - Update issue state"
            echo "  label <num> <labels...>  - Add labels to issue"
            echo "  comment <num> \"text\"   - Add comment to issue"
            echo "  list-issues [filter]     - List issues (optional: label filter)"
            echo ""
            echo "Examples:"
            echo "  ./github-api-helper.sh setup"
            echo "  ./github-api-helper.sh status"
            echo "  ./github-api-helper.sh update-issue 1234 closed"
            echo "  ./github-api-helper.sh label 1234 bug critical"
            echo ""
            ;;
        *)
            echo -e "${RED}✗ Unknown command: $cmd${NC}"
            echo "Run: ./github-api-helper.sh -h"
            return 1
            ;;
    esac
}

main "$@"
