[mypy]
strict = True
ignore_missing_imports = True
python_version = 3.12
exclude = venv

[mypy-torch.*]
ignore_missing_imports = True

[mypy-firebase_admin.*]
ignore_missing_imports = True

[mypy-opentelemetry.*]
ignore_missing_imports = True

[mypy-sentence_transformers.*]
ignore_missing_imports = True
