# Makefile for building top-level ollama binary

include make/common-defs.make

exe ollama: $(OLLAMA_EXE)
dist_exe dist_ollama: $(DIST_OLLAMA_EXE)

GO_DEPS=$(foreach dir,$(shell go list -deps -f '{{.Dir}}' ../ ),$(wildcard $(dir)/*.go))
CPU_GOFLAGS="-ldflags=-w -s \"-X=github.com/ollama/ollama/version.Version=$(VERSION)\" \"-X=github.com/ollama/ollama/llama.CpuFeatures=$(subst $(space),$(comma),$(TARGET_CPU_FLAGS))\" $(TARGET_LDFLAGS)"
PAYLOADS=$(wildcard $(RUNNERS_PAYLOAD_DIR)/*/*.gz)

$(OLLAMA_EXE) $(DIST_OLLAMA_EXE): TARGET_CPU_FLAGS=$(CUSTOM_CPU_FLAGS)
$(OLLAMA_EXE) $(DIST_OLLAMA_EXE): $(COMMON_SRCS) $(COMMON_HDRS) $(PAYLOADS) $(GO_DEPS) 
	cd .. && GOARCH=$(ARCH) go build -buildmode=pie $(CPU_GOFLAGS) -trimpath $(if $(CUSTOM_CPU_FLAGS),-tags $(subst $(space),$(comma),$(CUSTOM_CPU_FLAGS)))  -o $(patsubst ../%,%,$@) .

.PHONY: ollama dist_ollama exe dist_exe

# Handy debugging for make variables
print-%:
	@echo '$*=$($*)'
