name: Model request
description: Request a new model for the library
title: ""
labels: [mr]
body:
  - type: markdown
    attributes:
      value: |
        Please check if your Model request is [already available](https://ollama.com/search) or that you cannot [import it](https://github.com/ollama/ollama/blob/main/docs/import.md#import-a-model) yourself.
        Tell us about which Model you'd like to see in the library!
  - type: textarea
    id: problem
    attributes:
      label: What model would you like?
      description: Please provide a link to the model.
  - type: markdown
    attributes:
      value: |
        Thanks for filing a model request!
