//go:build tqdiag

// Package turboquant diagnostic: Phase 1 of the qwen2.5:7b tq3k fix plan.
// Runs four K-encoder variants against synthesized qwen2-like and llama-like
// K distributions, reports rel-dot-error and distribution stats, and lets
// the operator pick the right Phase 2 sub-phase from empirical data.
//
// Build-gated so normal `go test ./turboquant/...` doesn't pull it in:
//
//	go test -tags tqdiag -run TestDiagQwen2KPhase1 -v ./turboquant/...
//
// Required env vars:
//
//	TQ_MODEL_PATH_QWEN25_7B=/usr/share/ollama/.ollama/models/blobs/sha256-2bada8a7450677000f678be90653b85d364de7db25eb5ea54136ada5f3933730
//	TQ_MODEL_PATH_LLAMA32_3B=/usr/share/ollama/.ollama/models/blobs/sha256-dde5aa3fc5ffc17176b5e8bdc82f587b24b2678c6c66101bf7da77af9f7ccdff
//
// Output:
//
//	- stdout: markdown table per model: (layer, head) × variant → metrics
//	- /tmp/tq_diag_phase1.md: same data, committed as Phase 1 evidence

package turboquant

import (
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"testing"

	"github.com/ollama/ollama/fs/gguf"
)

// ── model metadata (hardcoded; avoids fragile gguf key probing) ─────────────

type modelMeta struct {
	name       string
	hiddenSize int
	numKVHeads int
	headDim    int
	numLayers  int
	hasBias    bool // attn_k.bias present
}

var (
	qwen25_7b  = modelMeta{name: "qwen2.5:7b", hiddenSize: 3584, numKVHeads: 4, headDim: 128, numLayers: 28, hasBias: true}
	llama32_3b = modelMeta{name: "llama3.2:3b", hiddenSize: 3072, numKVHeads: 8, headDim: 128, numLayers: 28, hasBias: false}
)

// ── entry point ────────────────────────────────────────────────────────────

func TestDiagQwen2KPhase1(t *testing.T) {
	qwenPath := os.Getenv("TQ_MODEL_PATH_QWEN25_7B")
	llamaPath := os.Getenv("TQ_MODEL_PATH_LLAMA32_3B")
	if qwenPath == "" || llamaPath == "" {
		t.Skip("set TQ_MODEL_PATH_QWEN25_7B and TQ_MODEL_PATH_LLAMA32_3B to run; see file header for paths")
	}

	out, err := os.Create("/tmp/tq_diag_phase1.md")
	if err != nil {
		t.Fatalf("create output file: %v", err)
	}
	defer out.Close()
	w := io.MultiWriter(out, os.Stdout)

	fmt.Fprintf(w, "# TQ Diagnostic Phase 1 — qwen2.5:7b vs llama3.2:3b\n\n")
	fmt.Fprintf(w, "Generated by turboquant/diag_qwen2k_test.go\n\n")
	fmt.Fprintf(w, "Metrics per (layer, head, variant): `relDotErr` median across 256 trials. ")
	fmt.Fprintf(w, "`maxSingletonEnergy` = max_i(r_i²)/sum_j(r_j²) of the rotated K. ")
	fmt.Fprintf(w, "`p99p50` = p99(|rotated|)/p50(|rotated|). ")
	fmt.Fprintf(w, "`biasCV` = stddev_across_trials(rotated) / (|mean_across_trials| + eps) averaged per dim — low = stable per-head bias.\n\n")

	qResults := runDiagnostic(t, w, qwenPath, qwen25_7b)
	lResults := runDiagnostic(t, w, llamaPath, llama32_3b)

	// Emit a summary comparison at the end.
	fmt.Fprintf(w, "\n## Summary comparison\n\n")
	fmt.Fprintf(w, "| model | median Var.A relDotErr | median Var.B relDotErr | median Var.C relDotErr | median Var.D relDotErr |\n")
	fmt.Fprintf(w, "|---|---|---|---|---|\n")
	for _, r := range []struct {
		name string
		rows []diagRow
	}{{"qwen2.5:7b", qResults}, {"llama3.2:3b", lResults}} {
		medA := medianField(r.rows, func(row diagRow) float64 { return row.variantA.relDotErr })
		medB := medianField(r.rows, func(row diagRow) float64 { return row.variantB.relDotErr })
		medC := medianField(r.rows, func(row diagRow) float64 { return row.variantC.relDotErr })
		medD := medianField(r.rows, func(row diagRow) float64 { return row.variantD.relDotErr })
		fmt.Fprintf(w, "| %s | %.4f | %.4f | %.4f | %.4f |\n", r.name, medA, medB, medC, medD)
	}

	// Decision gate guidance.
	fmt.Fprintf(w, "\n## Decision gates (read /home/mike/.claude/plans/happy-dazzling-nova.md Phase 1.5)\n\n")
	fmt.Fprintf(w, "- Gate A fires if qwen Var.A ≤ 1.2× llama Var.A (bug not in per-head encode).\n")
	fmt.Fprintf(w, "- Gate B fires if qwen Var.D drops ≥50%% vs qwen Var.A (static bias fix wins → Phase 2D).\n")
	fmt.Fprintf(w, "- Gate C fires if qwen Var.C recovers within 1.2× of llama Var.A (post-rotation split → Phase 2C).\n")
	fmt.Fprintf(w, "- Gate D fires if only Var.B helps but not Var.C (CPU-domain split → Phase 2B, needs advisor).\n")
	fmt.Fprintf(w, "- Gate E fires if nothing helps (call advisor).\n")
}

// ── core diagnostic ────────────────────────────────────────────────────────

type variantResult struct {
	relDotErr float64 // median across trials
}

type diagRow struct {
	layer    int
	headIdx  int
	variantA variantResult
	variantB variantResult
	variantC variantResult
	variantD variantResult

	// distribution stats on the rotated K (median across trials)
	maxSingletonEnergy float64
	p99p50             float64
	biasCV             float64 // low = per-head bias is stable across trials
}

func runDiagnostic(t *testing.T, w io.Writer, path string, meta modelMeta) []diagRow {
	t.Helper()
	fmt.Fprintf(w, "\n## Model: %s (hidden=%d, numKVHeads=%d, headDim=%d, numLayers=%d, hasBias=%v)\n\n",
		meta.name, meta.hiddenSize, meta.numKVHeads, meta.headDim, meta.numLayers, meta.hasBias)

	f, err := gguf.Open(path)
	if err != nil {
		t.Fatalf("gguf.Open %s: %v", path, err)
	}

	// Sample 5 layers evenly: {0, L/4, L/2, 3L/4, L-1}
	L := meta.numLayers
	sampled := []int{0, L / 4, L / 2, (3 * L) / 4, L - 1}
	// Dedup while preserving order (small L edge cases).
	seen := map[int]bool{}
	var layers []int
	for _, l := range sampled {
		if !seen[l] {
			layers = append(layers, l)
			seen[l] = true
		}
	}

	const trials = 256
	rng := splitmix64(0xd1a6c0570b1a51de)

	// Build the rotation once per headDim.
	rot := BuildRotation(meta.headDim, PresetTQ3K.RotationSeed)

	var rows []diagRow
	for _, layerIdx := range layers {
		biasHead := loadBiasForLayer(t, f, layerIdx, meta)
		for headIdx := 0; headIdx < meta.numKVHeads; headIdx++ {
			var b_h []float32
			if meta.hasBias {
				b_h = biasHead[headIdx*meta.headDim : (headIdx+1)*meta.headDim]
			} else {
				b_h = make([]float32, meta.headDim) // zero bias for llama
			}

			// Synthetic weights W_h ∈ R^{headDim × hiddenSize} with Xavier-ish init.
			// Variance = 1/hiddenSize so k_pre-bias ~ N(0, I).
			stddev := float32(1.0 / math.Sqrt(float64(meta.hiddenSize)))
			W_h := make([]float32, meta.headDim*meta.hiddenSize)
			for i := range W_h {
				W_h[i] = float32(gaussianFloat64(&rng)) * stddev
			}

			// Draw trials activations, compute k_head = W_h @ a + b_h, rotate.
			rotatedTrials := make([][]float32, trials)
			activations := make([][]float32, trials)
			queries := make([][]float32, trials)
			for tr := 0; tr < trials; tr++ {
				a := make([]float32, meta.hiddenSize)
				for j := range a {
					a[j] = float32(gaussianFloat64(&rng))
				}
				q := make([]float32, meta.headDim)
				for j := range q {
					q[j] = float32(gaussianFloat64(&rng)) / float32(math.Sqrt(float64(meta.headDim)))
				}
				activations[tr] = a
				queries[tr] = q

				k := make([]float32, meta.headDim)
				for out := 0; out < meta.headDim; out++ {
					var sum float32
					wRow := W_h[out*meta.hiddenSize : (out+1)*meta.hiddenSize]
					for in := 0; in < meta.hiddenSize; in++ {
						sum += wRow[in] * a[in]
					}
					k[out] = sum + b_h[out]
				}
				rotatedTrials[tr] = ApplyRotation(k, rot)
			}

			// ── Variant D setup: compute per-head rotated bias as the mean
			// across trials (static estimate). In a real implementation this
			// would be measured from the first forward-pass batch.
			biasEstimate := make([]float32, meta.headDim)
			for _, rk := range rotatedTrials {
				for i, v := range rk {
					biasEstimate[i] += v
				}
			}
			for i := range biasEstimate {
				biasEstimate[i] /= float32(trials)
			}

			// ── distribution stats on the rotated K (median across trials) ─
			var maxSingletonEnergies, p99p50s []float64
			var biasCV float64
			{
				// bias stability across trials: mean abs deviation from mean
				var meanAbsDev float64
				var meanAbsMean float64
				for tr := 0; tr < trials; tr++ {
					for i := 0; i < meta.headDim; i++ {
						meanAbsDev += math.Abs(float64(rotatedTrials[tr][i] - biasEstimate[i]))
					}
				}
				meanAbsDev /= float64(trials * meta.headDim)
				for i := 0; i < meta.headDim; i++ {
					meanAbsMean += math.Abs(float64(biasEstimate[i]))
				}
				meanAbsMean /= float64(meta.headDim)
				biasCV = meanAbsDev / (meanAbsMean + 1e-8)
			}
			for tr := 0; tr < trials; tr++ {
				rk := rotatedTrials[tr]
				var sumSq float64
				for _, v := range rk {
					sumSq += float64(v) * float64(v)
				}
				if sumSq < 1e-20 {
					continue
				}
				var maxSq float64
				for _, v := range rk {
					if s := float64(v) * float64(v); s > maxSq {
						maxSq = s
					}
				}
				maxSingletonEnergies = append(maxSingletonEnergies, maxSq/sumSq)
				// p99 / p50 of |rotated|
				abs := make([]float64, meta.headDim)
				for i, v := range rk {
					abs[i] = math.Abs(float64(v))
				}
				sort.Float64s(abs)
				p50 := abs[meta.headDim/2]
				p99 := abs[meta.headDim-meta.headDim/100-1]
				if p50 < 1e-8 {
					p50 = 1e-8
				}
				p99p50s = append(p99p50s, p99/p50)
			}

			// ── run variants ─
			varA := runVariantA(rotatedTrials, queries, rot, meta.headDim)
			varB := runVariantB(rotatedTrials, queries, rot, meta.headDim, activations, W_h, b_h, meta)
			varC := runVariantC(rotatedTrials, queries, meta.headDim)
			varD := runVariantD(rotatedTrials, queries, biasEstimate, meta.headDim)

			row := diagRow{
				layer:              layerIdx,
				headIdx:            headIdx,
				variantA:           varA,
				variantB:           varB,
				variantC:           varC,
				variantD:           varD,
				maxSingletonEnergy: median(maxSingletonEnergies),
				p99p50:             median(p99p50s),
				biasCV:             biasCV,
			}
			rows = append(rows, row)
		}
	}

	// Emit markdown table.
	fmt.Fprintf(w, "| layer | head | VarA relErr | VarB relErr | VarC relErr | VarD relErr | maxSingle | p99p50 | biasCV |\n")
	fmt.Fprintf(w, "|---|---|---|---|---|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(w, "| %d | %d | %.4f | %.4f | %.4f | %.4f | %.4f | %.2f | %.3f |\n",
			r.layer, r.headIdx,
			r.variantA.relDotErr, r.variantB.relDotErr, r.variantC.relDotErr, r.variantD.relDotErr,
			r.maxSingletonEnergy, r.p99p50, r.biasCV)
	}

	return rows
}

// loadBiasForLayer returns the per-head concatenated bias vector for attn_k,
// or a zero slice if the model has no bias. Length = numKVHeads * headDim.
func loadBiasForLayer(t *testing.T, f *gguf.File, layerIdx int, meta modelMeta) []float32 {
	t.Helper()
	if !meta.hasBias {
		return make([]float32, meta.numKVHeads*meta.headDim)
	}
	name := fmt.Sprintf("blk.%d.attn_k.bias", layerIdx)
	info, r, err := f.TensorReader(name)
	if err != nil {
		t.Fatalf("TensorReader %s: %v", name, err)
	}
	if info.Type != gguf.TensorTypeF32 {
		t.Fatalf("%s expected F32, got %v", name, info.Type)
	}
	want := meta.numKVHeads * meta.headDim
	if info.NumValues() != int64(want) {
		t.Fatalf("%s shape mismatch: %d values, want %d", name, info.NumValues(), want)
	}
	buf := make([]byte, info.NumBytes())
	if _, err := io.ReadFull(r, buf); err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	out := make([]float32, want)
	for i := 0; i < want; i++ {
		bits := binary.LittleEndian.Uint32(buf[i*4 : (i+1)*4])
		out[i] = math.Float32frombits(bits)
	}
	return out
}

// ── encoder variants ───────────────────────────────────────────────────────

// Variant A: uniform per-head Lloyd-Max at 3 bits (current GPU path).
func runVariantA(rotated [][]float32, queries [][]float32, rot Rotation, headDim int) variantResult {
	const bits = 3
	codebook, boundaries := scalarCodebook(headDim, bits)
	var errs []float64
	for tr := range rotated {
		rk := rotated[tr]
		scale := blockScale(rk)
		dec := make([]float32, headDim)
		if scale > 0 {
			for i, v := range rk {
				idx := quantizeScalarByBoundary(v/scale, codebook, boundaries)
				dec[i] = dequantizeScalar(idx, codebook) * scale
			}
		}
		errs = append(errs, relDotErrRotSpace(queries[tr], rk, dec, rot))
	}
	return variantResult{relDotErr: median(errs)}
}

// Variant B: CPU reference with outlier split in ORIGINAL domain + QJL residual.
// Uses EncodeKeyVector → DecodeVector. For fair comparison we evaluate the
// reconstructed original-domain K against the original (un-rotated) k_h.
func runVariantB(rotated [][]float32, queries [][]float32, rot Rotation, headDim int, activations [][]float32, W_h []float32, b_h []float32, meta modelMeta) variantResult {
	var errs []float64
	for tr := range rotated {
		// Reconstruct original k_h from the rotated vector via inverse rotation.
		// (Cheaper than re-doing the matmul — rotation is orthogonal, lossless.)
		kOrig := ApplyInverseRotation(rotated[tr], rot)
		enc, err := EncodeKeyVector(kOrig, PresetTQ3K)
		if err != nil {
			continue
		}
		data, err := enc.MarshalBinary()
		if err != nil {
			continue
		}
		kRec, _, err := DecodeVector(data)
		if err != nil {
			continue
		}
		// Compute rel dot err in the ORIGINAL domain since Variant B reconstructs there.
		q := queries[tr]
		var trueDot, estDot float32
		for i := 0; i < headDim; i++ {
			trueDot += q[i] * kOrig[i]
			estDot += q[i] * kRec[i]
		}
		errs = append(errs, math.Abs(float64(estDot-trueDot))/(math.Abs(float64(trueDot))+1e-8))
	}
	return variantResult{relDotErr: median(errs)}
}

// Variant C: post-rotation top-K outlier split. Rotate once, take the top-K
// highest-|rotated| channels, encode them separately at 4 bits, rest at 3 bits.
// Uses the SAME rotation for both sub-blocks (this is the realistic GPU
// design — no second rotation matmul).
func runVariantC(rotated [][]float32, queries [][]float32, headDim int) variantResult {
	const regularBits = 3
	const outlierBits = 4
	const outlierCount = 16
	regCodebook, regBoundaries := scalarCodebook(headDim, regularBits)
	outCodebook, outBoundaries := scalarCodebook(headDim, outlierBits)

	var errs []float64
	for tr := range rotated {
		rk := rotated[tr]
		// Find top-K by abs magnitude.
		type indexed struct {
			idx int
			val float32
		}
		entries := make([]indexed, headDim)
		for i, v := range rk {
			entries[i] = indexed{idx: i, val: v}
		}
		sort.Slice(entries, func(i, j int) bool {
			return math.Abs(float64(entries[i].val)) > math.Abs(float64(entries[j].val))
		})
		isOutlier := make([]bool, headDim)
		for k := 0; k < outlierCount; k++ {
			isOutlier[entries[k].idx] = true
		}

		// Compute two scales: regular (non-outlier channels) and outlier.
		var regSumSq, outSumSq float64
		var regN, outN int
		for i, v := range rk {
			sq := float64(v) * float64(v)
			if isOutlier[i] {
				outSumSq += sq
				outN++
			} else {
				regSumSq += sq
				regN++
			}
		}
		regScale := float32(0)
		if regN > 0 && regSumSq > 1e-20 {
			regScale = float32(math.Sqrt(regSumSq / float64(regN)))
		}
		outScale := float32(0)
		if outN > 0 && outSumSq > 1e-20 {
			outScale = float32(math.Sqrt(outSumSq / float64(outN)))
		}

		dec := make([]float32, headDim)
		for i, v := range rk {
			if isOutlier[i] {
				if outScale > 0 {
					idx := quantizeScalarByBoundary(v/outScale, outCodebook, outBoundaries)
					dec[i] = dequantizeScalar(idx, outCodebook) * outScale
				}
			} else {
				if regScale > 0 {
					idx := quantizeScalarByBoundary(v/regScale, regCodebook, regBoundaries)
					dec[i] = dequantizeScalar(idx, regCodebook) * regScale
				}
			}
		}

		// Dot product in rotated space (Q is rotated the same way as K at inference).
		q := queries[tr]
		// Because we're comparing in rotated space, rotate q with the same R^T.
		qRot := applyRotationInPlace(q, headDim)
		_ = qRot
		// Actually — dot(q, k) = dot(R^T q, R^T k) since R is orthogonal. So
		// we can compare in rotated space directly using rk (the raw rotated
		// input) as ground truth.
		var trueDot, estDot float64
		for i := 0; i < headDim; i++ {
			trueDot += float64(q[i]) * float64(rk[i])
			estDot += float64(q[i]) * float64(dec[i])
		}
		errs = append(errs, math.Abs(estDot-trueDot)/(math.Abs(trueDot)+1e-8))
	}
	return variantResult{relDotErr: median(errs)}
}

// applyRotationInPlace returns a no-op rotation — the dot product in rotated
// vs original space is identical for orthogonal rotations, so Variant C
// compares q directly against rotated K. Kept as a placeholder to make the
// intent explicit in the Variant C body.
func applyRotationInPlace(x []float32, dim int) []float32 { return x }

// Variant D: static per-head bias subtract. Estimate bias = mean(rotated K)
// across trials, subtract before encoding, add back on decode. One f32 per
// head-dim stored per (layer, head) — no per-cell overhead.
func runVariantD(rotated [][]float32, queries [][]float32, biasEstimate []float32, headDim int) variantResult {
	const bits = 3
	codebook, boundaries := scalarCodebook(headDim, bits)
	var errs []float64
	for tr := range rotated {
		rk := rotated[tr]
		centered := make([]float32, headDim)
		for i := range rk {
			centered[i] = rk[i] - biasEstimate[i]
		}
		scale := blockScale(centered)
		dec := make([]float32, headDim)
		if scale > 0 {
			for i, v := range centered {
				idx := quantizeScalarByBoundary(v/scale, codebook, boundaries)
				dec[i] = dequantizeScalar(idx, codebook)*scale + biasEstimate[i]
			}
		} else {
			copy(dec, biasEstimate)
		}
		q := queries[tr]
		var trueDot, estDot float64
		for i := 0; i < headDim; i++ {
			trueDot += float64(q[i]) * float64(rk[i])
			estDot += float64(q[i]) * float64(dec[i])
		}
		errs = append(errs, math.Abs(estDot-trueDot)/(math.Abs(trueDot)+1e-8))
	}
	return variantResult{relDotErr: median(errs)}
}

// ── helpers ────────────────────────────────────────────────────────────────

// relDotErrRotSpace: evaluate |q·k_est − q·k_true|/|q·k_true| in rotated space.
// Rotation is orthogonal so the raw q is rotated on the Q side at inference;
// for the diagnostic we skip that rotation and operate entirely in rotated
// space using the provided rotated K values. See Variant C comment for why.
func relDotErrRotSpace(q, rk, dec []float32, _ Rotation) float64 {
	var trueDot, estDot float64
	for i := range rk {
		trueDot += float64(q[i]) * float64(rk[i])
		estDot += float64(q[i]) * float64(dec[i])
	}
	return math.Abs(estDot-trueDot) / (math.Abs(trueDot) + 1e-8)
}

func median(xs []float64) float64 {
	if len(xs) == 0 {
		return 0
	}
	sorted := make([]float64, len(xs))
	copy(sorted, xs)
	sort.Float64s(sorted)
	return sorted[len(sorted)/2]
}

func medianField(rows []diagRow, f func(diagRow) float64) float64 {
	xs := make([]float64, 0, len(rows))
	for _, r := range rows {
		xs = append(xs, f(r))
	}
	return median(xs)
}
