package i18n

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// errTemplates lists English printf-style message templates generated by
// cobra, pflag and the Modelfile parser. They are matched as prefixes because
// cobra appends suggestion blocks and the parser appends line context; the
// Chinese counterparts live in the catalog under the same English keys.
var errTemplates = []string{
	`unknown command %q for %q`,
	`requires at least %d arg(s), only received %d`,
	`accepts %d arg(s), received %d`,
	`unknown flag: --%s`,
	`unknown shorthand flag: %q in -%s`,
	`flag needs an argument: %s`,
	`flag needs an argument: %q in -%s`,
	`invalid argument %q for %q flag: %v`,
	`no FROM line`,
	`no Modelfile or safetensors files found`,
	`message role must be one of "system", "user", or "assistant"`,
	`command must be one of "from", "license", "template", "system", "adapter", "draft", "renderer", "parser", "parameter", "message", or "requires"`,
	`requires must be a valid semver (e.g. 0.14.0)`,
	`%s must not reference the same local path as FROM: %s`,
	"insecure path: %s\n\nUse --local-dir <dir> when downloading model to disable caching",
	`insecure path: %s`,
	`invalid content type: expected %s for %s`,
	`malformed public key`,
	`unexpected EOF: %s`,
	`failed to get current user: %w`,
	`failed to find user '%s': %w`,
	`template error`,
	`invalid requires version`,
	`license must be a string or a list of strings`,
	`unsupported MLX architecture`,
}

// errPhrases lists verb-free English fragments that appear inside otherwise
// untranslated messages; cobra appends its suggestion block to the
// unknown-command error.
var errPhrases = []string{
	`Did you mean this?`,
}

// parserLinePrefix matches the "(line N): " prefix the Modelfile parser adds
// around an inner message, so the inner message can be translated while the
// prefix is preserved.
var parserLinePrefix = regexp.MustCompile(`^\(line (\d+)\): `)

// translateMessage rewrites an English library error message using the
// template catalog. It returns the input unchanged when nothing matches.
func translateMessage(msg string) string {
	if Locale() != "zh" {
		return msg
	}
	// Split an optional parser line prefix; translate the inner message only.
	prefix := ""
	if loc := parserLinePrefix.FindStringSubmatch(msg); loc != nil {
		if n, err := strconv.Atoi(loc[1]); err == nil {
			prefix = fmt.Sprintf(T("(line %d): "), n)
		} else {
			prefix = loc[0]
		}
		msg = msg[len(loc[0]):]
	}

	for _, tpl := range errTemplates {
		captures, rest, ok := matchTemplate(tpl, msg)
		if !ok {
			continue
		}
		zh, ok := messages()[tpl]
		if !ok {
			continue
		}
		return prefix + fillTemplate(zh, captures) + translateTail(rest)
	}
	return prefix + translateTail(msg)
}

// translateTail rewrites plain (verb-free) fragments such as cobra's
// suggestion header inside the untranslated remainder of a message.
func translateTail(s string) string {
	for _, phrase := range errPhrases {
		if zh, ok := messages()[phrase]; ok {
			s = strings.ReplaceAll(s, phrase, zh)
		}
	}
	return s
}

// matchTemplate matches msg against an English printf template from the start
// and returns the captured arguments plus the untranslated remainder. The
// final verb captures to the end of the line so trailing suggestion blocks
// survive; earlier verbs stop at the following literal text.
func matchTemplate(tmpl, msg string) (captures []string, rest string, ok bool) {
	pattern := templatePattern(tmpl)
	re, err := regexp.Compile(pattern)
	if err != nil {
		return nil, "", false
	}
	m := re.FindStringSubmatch(msg)
	if m == nil {
		return nil, "", false
	}
	caps := m[1:]
	// Normalize quoted captures ("x" or 'x') to the bare value so Chinese
	// templates can re-quote with full-width quotes via %s.
	for i, c := range caps {
		if len(c) >= 2 {
			if (c[0] == '"' && c[len(c)-1] == '"') || (c[0] == '\'' && c[len(c)-1] == '\'') {
				caps[i] = c[1 : len(c)-1]
			}
		}
	}
	return caps, msg[len(m[0]):], true
}

// templatePattern converts a printf-style template into an anchored regular
// expression whose capture groups correspond 1:1 to the template's verbs.
func templatePattern(tmpl string) string {
	var b strings.Builder
	b.WriteString(`^`)
	segs := parseTemplate(tmpl)
	for i, seg := range segs {
		if seg.verb == "" {
			b.WriteString(regexp.QuoteMeta(seg.lit))
			continue
		}
		last := i == len(segs)-1
		switch seg.verb[len(seg.verb)-1] {
		case 'q':
			// pflag formats shorthand flags with %q on a byte ('x'),
			// cobra formats strings with %q ("x"); match either.
			b.WriteString(`("[^"\n]*"|'[^'\n]*')`)
		case 'd', 'b', 'o', 'O', 'x', 'X':
			b.WriteString(`(\d+)`)
		default:
			if last {
				b.WriteString(`(.+)`)
			} else {
				b.WriteString(`([^\n]+?)`)
			}
		}
	}
	return b.String()
}

// templateSeg is one piece of a printf-style template: either literal text or
// a verb such as "%q" or "%[2]s".
type templateSeg struct {
	lit  string
	verb string // empty for literal segments
}

// parseTemplate splits a printf-style template into literal and verb segments,
// handling %[n] indices, flags, width and precision (e.g. "%-[3] 5.2f").
func parseTemplate(t string) []templateSeg {
	var segs []templateSeg
	var lit strings.Builder
	for i := 0; i < len(t); {
		if t[i] != '%' {
			lit.WriteByte(t[i])
			i++
			continue
		}
		j := i + 1
		if j < len(t) && t[j] == '[' { // explicit argument index
			for j < len(t) && t[j] != ']' {
				j++
			}
			if j < len(t) {
				j++
			}
		}
		for j < len(t) && strings.ContainsRune("-+#0 ", rune(t[j])) {
			j++
		}
		for j < len(t) && (t[j] == '*' || (t[j] >= '0' && t[j] <= '9') || t[j] == '.') {
			j++
		}
		if j < len(t) && t[j] == '%' && j == i+1 { // literal %%
			lit.WriteString("%%")
			i = j + 1
			continue
		}
		if j >= len(t) {
			lit.WriteByte('%')
			i++
			continue
		}
		if lit.Len() > 0 {
			segs = append(segs, templateSeg{lit: lit.String()})
			lit.Reset()
		}
		segs = append(segs, templateSeg{verb: t[i : j+1]})
		i = j + 1
	}
	if lit.Len() > 0 {
		segs = append(segs, templateSeg{lit: lit.String()})
	}
	return segs
}

// wVerb matches a %w-style verb so translations can render it as %s.
var wVerb = regexp.MustCompile(`%((?:\[[0-9]+\])?[-+#0 ']*(?:[0-9]+|\*)?(?:\.(?:[0-9]+|\*))?)w`)

// fillTemplate formats the Chinese template with the captured arguments.
// Chinese templates keep the verb count and kinds of their English source
// (enforced by the package tests); captures arrive as strings and are coerced
// to the verb kind the Chinese template expects.
func fillTemplate(zh string, captures []string) string {
	// Captures are already-rendered text; %w wrapping is meaningless here and
	// fmt.Sprintf would render "%!w(...)", so normalize it to %s.
	zh = wVerb.ReplaceAllString(zh, "%${1}s")
	args := make([]any, 0, len(captures))
	i := 0
	for _, seg := range parseTemplate(zh) {
		if seg.verb == "" {
			continue
		}
		if i >= len(captures) {
			return zh // malformed translation: fall back to English
		}
		c := captures[i]
		if len(c) >= 2 {
			if (c[0] == '"' && c[len(c)-1] == '"') || (c[0] == '\'' && c[len(c)-1] == '\'') {
				c = c[1 : len(c)-1]
			}
		}
		i++
		switch seg.verb[len(seg.verb)-1] {
		case 'd', 'b', 'o', 'O', 'x', 'X':
			n, err := strconv.Atoi(c)
			if err != nil {
				return zh
			}
			args = append(args, n)
		default:
			args = append(args, c)
		}
	}
	return fmt.Sprintf(zh, args...)
}
