// Copyright 2026 Muvon Un Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package launch

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/ollama/ollama/cmd/internal/fileutil"
)

// Octomind implements Runner and Editor for Octomind integration
type Octomind struct{}

func (o *Octomind) String() string {
	return "Octomind"
}

func (o *Octomind) Run(model string, args []string) error {
	if _, err := exec.LookPath("octomind"); err != nil {
		return fmt.Errorf("octomind is not installed, install from https://muvon.io")
	}

	cmd := exec.Command("octomind", "session")
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	// Set Ollama API endpoint for Octomind
	cmd.Env = append(os.Environ(),
		"OLLAMA_API_KEY=ollama",
	)

	return cmd.Run()
}

func (o *Octomind) Paths() []string {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}

	// Octomind uses XDG config directory
	p := filepath.Join(home, ".config", "octomind", "config.toml")
	if _, err := os.Stat(p); err == nil {
		return []string{p}
	}

	return nil
}

func (o *Octomind) Edit(models []string) error {
	if len(models) == 0 {
		return nil
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	configDir := filepath.Join(home, ".config", "octomind")
	configPath := filepath.Join(configDir, "config.toml")

	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return err
	}

	// Octomind uses TOML config with model = "provider:model" format
	// Set Ollama as the provider with the selected model
	config := fmt.Sprintf(`# Octomind Configuration - Generated by ollama launch
model = "ollama:%s"

[providers.ollama]
# Ollama uses OpenAI-compatible API at localhost:11434
`, models[0])

	// Check if file exists and preserve user settings
	if data, err := os.ReadFile(configPath); err == nil {
		// Parse existing config and update model
		content := string(data)
		lines := strings.Split(content, "\n")
		var newLines []string
		for _, line := range lines {
			// Skip old model line and generated section
			if strings.HasPrefix(line, "model = ") && strings.Contains(line, "ollama:") {
				newLines = append(newLines, fmt.Sprintf(`model = "ollama:%s"`, models[0]))
				continue
			}
			// Skip old generated section marker
			if strings.HasPrefix(line, "# Generated by ollama launch") {
				continue
			}
			// Skip old providers.ollama section (we'll regenerate)
			if strings.HasPrefix(line, "[providers.ollama]") {
				// Skip until next section
				continue
			}
			newLines = append(newLines, line)
		}
		config = strings.Join(newLines, "\n")
	}

	return fileutil.WriteWithBackup(configPath, []byte(config))
}

func (o *Octomind) Models() []string {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}

	configPath := filepath.Join(home, ".config", "octomind", "config.toml")
	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil
	}

	// Parse TOML to extract ollama models
	// Look for model = "ollama:model_name" pattern
	content := string(data)
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, `model = "ollama:`) {
			// Extract model name
			model := strings.TrimPrefix(line, `model = "ollama:`)
			model = strings.TrimSuffix(model, `"`)
			model = strings.TrimSpace(model)
			if model != "" {
				return []string{model}
			}
		}
	}

	return nil
}