# Targets to assist in running tests

include make/common-defs.make

test:
	cd .. && go test ./... 

integration: $(OLLAMA_EXE)
	cd .. && go test --tags=integration ./integration -v

lint:
	cd .. && golangci-lint run -v

# Note: in this makefile we error instead of building to allow more fine-grain control of testing flows
$(OLLAMA_EXE):
	@echo ""
	@echo "ERROR: You must build ollama first - use 'make all' to build the ollama binaries"
	@echo ""
	@exit 1