# Build rules for CUDA v12 runner

include make/common-defs.make
include make/cuda-v12-defs.make

GPU_RUNNER_VARIANT := _v12
GPU_COMPILER=$(CUDA_12_COMPILER)
CUDA_ARCHITECTURES?=60;61;62;70;72;75;80;86;87;89;90;90a
GPU_LIB_DIR = $(CUDA_12_LIB_DIR)
CGO_EXTRA_LDFLAGS = $(CUDA_12_CGO_EXTRA_LDFLAGS)

include make/cuda.make
include make/gpu.make