# Build rules for CUDA v11 runner

include make/common-defs.make
include make/cuda-v11-defs.make

GPU_RUNNER_VARIANT := _v11
GPU_COMPILER=$(CUDA_11_COMPILER)
CUDA_ARCHITECTURES?=50;52;53;60;61;62;70;72;75;80;86
GPU_LIB_DIR = $(CUDA_11_LIB_DIR)
CGO_EXTRA_LDFLAGS = $(CUDA_11_CGO_EXTRA_LDFLAGS)

include make/cuda.make
include make/gpu.make