package autotune

import (
	"fmt"
	"log/slog"
	"runtime"
	"time"
)

const (
	MiB = 1024 * 1024
	GiB = 1024 * MiB
)

// Recommendation is a single environment-variable-level setting.
type Recommendation struct {
	Key    string
	Value  string
	Reason string
}

// TunePlan is the full set of recommendations generated by the tuner.
type TunePlan struct {
	Profile         Profile
	Hardware        HardwareProfile
	Recommendations []Recommendation

	// Computed optimal values (used by the integration layer).
	FlashAttention  bool
	KvCacheType     string
	NumParallel     uint
	MaxLoadedModels uint
	KeepAlive       time.Duration
	GpuOverhead     uint64
	MaxQueue        uint
	MultiUserCache  bool
	SchedSpread     bool
	ContextLength   uint
}

// Tune analyses hardware and profile, returning an optimal TunePlan.
func Tune(hw HardwareProfile, profile Profile) *TunePlan {
	cfg := profileConfigs()[profile]
	plan := &TunePlan{
		Profile:  profile,
		Hardware: hw,
	}

	// --- Flash Attention ---
	faEnabled := resolveFlashAttention(hw, cfg)
	plan.FlashAttention = faEnabled
	if faEnabled {
		plan.addRec("OLLAMA_FLASH_ATTENTION", "true",
			"enable fused attention kernels for faster inference")
	}

	// --- KV Cache Type ---
	kvType := resolveKvCacheType(hw, cfg, faEnabled)
	plan.KvCacheType = kvType
	if kvType != "" && kvType != "f16" {
		savings := estimateKvSavings(kvType)
		plan.addRec("OLLAMA_KV_CACHE_TYPE", kvType,
			"quantized KV cache: ~"+savings+" VRAM savings per 8K context")
	}

	// --- Parallel Slots ---
	np := resolveNumParallel(hw, cfg)
	plan.NumParallel = np
	if np > 0 {
		plan.addRec("OLLAMA_NUM_PARALLEL", uintStr(np),
			"parallel inference slots (VRAM-aware)")
	}

	// --- Max Loaded Models ---
	mlm := resolveMaxLoadedModels(hw, cfg)
	plan.MaxLoadedModels = mlm
	if mlm > 0 {
		plan.addRec("OLLAMA_MAX_LOADED_MODELS", uintStr(mlm),
			"max concurrent models in memory")
	}

	// --- Keep Alive ---
	ka := resolveKeepAlive(cfg)
	plan.KeepAlive = ka
	if ka > 0 {
		plan.addRec("OLLAMA_KEEP_ALIVE", durationStr(ka),
			"model idle timeout")
	}

	// --- GPU Overhead ---
	overhead := resolveGpuOverhead(hw, cfg)
	plan.GpuOverhead = overhead
	if overhead > 0 {
		plan.addRec("OLLAMA_GPU_OVERHEAD", uint64Str(overhead),
			"reserve VRAM per GPU for driver/compositor stability")
	}

	// --- Max Queue ---
	mq := resolveMaxQueue(cfg)
	plan.MaxQueue = mq
	if mq > 0 {
		plan.addRec("OLLAMA_MAX_QUEUE", uintStr(mq),
			"request queue depth")
	}

	// --- Multi-User Cache ---
	mu := resolveMultiUserCache(cfg)
	plan.MultiUserCache = mu
	if mu {
		plan.addRec("OLLAMA_MULTIUSER_CACHE", "true",
			"shared prompt cache for concurrent users")
	}

	// --- Sched Spread ---
	spread := resolveSchedSpread(hw, cfg)
	plan.SchedSpread = spread
	if spread {
		plan.addRec("OLLAMA_SCHED_SPREAD", "true",
			"spread model across all GPUs")
	}

	// --- Context Length ---
	ctx := resolveContextLength(hw, cfg)
	plan.ContextLength = ctx
	if ctx > 0 {
		plan.addRec("OLLAMA_CONTEXT_LENGTH", uintStr(ctx),
			"context window sized to available memory")
	}

	slog.Info("autotune plan generated",
		"profile", string(profile),
		"hardware", hw.Summary(),
		"recommendations", len(plan.Recommendations),
	)

	return plan
}

// ----- Resolution helpers -----

func resolveFlashAttention(hw HardwareProfile, cfg ProfileConfig) bool {
	if cfg.FlashAttention != nil {
		want := *cfg.FlashAttention
		if want && !hw.FlashAttentionCapable() {
			slog.Warn("autotune: flash attention requested but not supported by hardware")
			return false
		}
		return want
	}
	// Auto: enable if hardware supports it
	return hw.FlashAttentionCapable()
}

func resolveKvCacheType(hw HardwareProfile, cfg ProfileConfig, faEnabled bool) string {
	kvType := cfg.KvCacheType
	if kvType == "" {
		// Auto: use q8_0 if FA is enabled (quantized KV requires FA)
		if faEnabled {
			kvType = "q8_0"
		} else {
			kvType = "f16"
		}
	}
	// Quantized KV cache requires flash attention
	if kvType != "f16" && !faEnabled {
		slog.Warn("autotune: quantized KV cache needs flash attention, falling back to f16",
			"requested", kvType)
		return "f16"
	}
	return kvType
}

func resolveNumParallel(hw HardwareProfile, cfg ProfileConfig) uint {
	if cfg.NumParallel > 0 {
		return cfg.NumParallel
	}
	// Auto-compute based on VRAM
	if !hw.HasGPU() {
		// CPU-only: keep it low
		return 1
	}
	smallest := hw.SmallestGPUVRAM()
	switch {
	case smallest >= 24*GiB:
		return 4
	case smallest >= 12*GiB:
		return 2
	case smallest >= 8*GiB:
		return 2
	default:
		return 1
	}
}

func resolveMaxLoadedModels(hw HardwareProfile, cfg ProfileConfig) uint {
	if cfg.MaxLoadedModels > 0 {
		return cfg.MaxLoadedModels
	}
	// Auto: based on GPU count and VRAM
	gpuCount := hw.DiscreteGPUCount()
	if gpuCount == 0 {
		return 1
	}
	totalVRAM := hw.TotalVRAM()
	switch {
	case totalVRAM >= 48*GiB:
		return uint(gpuCount) * 3
	case totalVRAM >= 24*GiB:
		return uint(gpuCount) * 2
	case totalVRAM >= 12*GiB:
		return uint(gpuCount)
	default:
		return 1
	}
}

func resolveKeepAlive(cfg ProfileConfig) time.Duration {
	if cfg.KeepAlive > 0 {
		return cfg.KeepAlive
	}
	return 5 * time.Minute
}

func resolveGpuOverhead(hw HardwareProfile, cfg ProfileConfig) uint64 {
	if cfg.GpuOverhead > 0 {
		return cfg.GpuOverhead
	}
	if !hw.HasGPU() {
		return 0
	}
	// Auto: reserve based on OS (windowing systems need compositor memory)
	switch runtime.GOOS {
	case "windows":
		return 450 * MiB
	case "linux":
		// Wayland/X11 compositors use some VRAM
		return 200 * MiB
	default:
		// macOS Metal: apple handles it
		return 0
	}
}

func resolveMaxQueue(cfg ProfileConfig) uint {
	if cfg.MaxQueue > 0 {
		return cfg.MaxQueue
	}
	return 512
}

func resolveMultiUserCache(cfg ProfileConfig) bool {
	if cfg.MultiUserCache != nil {
		return *cfg.MultiUserCache
	}
	return false
}

func resolveSchedSpread(hw HardwareProfile, cfg ProfileConfig) bool {
	if cfg.SchedSpread != nil {
		return *cfg.SchedSpread
	}
	// Auto: spread only if multiple discrete GPUs of similar size
	if hw.DiscreteGPUCount() < 2 {
		return false
	}
	return true
}

func resolveContextLength(hw HardwareProfile, cfg ProfileConfig) uint {
	if cfg.ContextLength > 0 {
		return cfg.ContextLength
	}
	// Auto: use VRAM-based heuristics
	if hw.HasGPU() {
		smallest := hw.SmallestGPUVRAM()
		switch {
		case smallest >= 24*GiB:
			return 32768
		case smallest >= 12*GiB:
			return 8192
		case smallest >= 8*GiB:
			return 4096
		default:
			return 2048
		}
	}
	// CPU-only: moderate context
	if hw.System.TotalMemory >= 32*GiB {
		return 8192
	}
	return 4096
}

func estimateKvSavings(kvType string) string {
	switch kvType {
	case "q8_0":
		return "50%"
	case "q4_0":
		return "75%"
	default:
		return "some"
	}
}

// ----- formatting helpers -----

func (p *TunePlan) addRec(key, value, reason string) {
	p.Recommendations = append(p.Recommendations, Recommendation{
		Key:    key,
		Value:  value,
		Reason: reason,
	})
}

func uintStr(n uint) string {
	return fmt.Sprintf("%d", n)
}

func uint64Str(n uint64) string {
	return fmt.Sprintf("%d", n)
}

func durationStr(d time.Duration) string {
	if d >= time.Hour {
		return fmt.Sprintf("%dh", int(d.Hours()))
	}
	return fmt.Sprintf("%dm", int(d.Minutes()))
}
