package gliner

import (
	"context"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"testing"

	"github.com/ollama/ollama/api"
	"github.com/ollama/ollama/mlx"
	"github.com/ollama/ollama/mlx/mlxtest"
)

func readJSON(t *testing.T, path string, v any) {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err = json.Unmarshal(b, v); err != nil {
		t.Fatal(err)
	}
}

func closeFloats(t *mlxtest.T, got, want []float32, tolerance float64) {
	t.Helper()
	if len(got) != len(want) {
		t.Fatalf("length %d, expected %d", len(got), len(want))
	}
	var maxError float64
	for i, v := range got {
		d := math.Abs(float64(v - want[i]))
		if math.IsNaN(float64(v)) || d > tolerance {
			t.Fatalf("value %d = %g, expected %g (error %g)", i, v, want[i], d)
		}
		maxError = max(maxError, d)
	}
	t.Logf("maximum absolute error: %.8g", maxError)
}

func loadTestWeights(t *mlxtest.T, m *Model, path string) {
	t.Helper()
	w := make(map[string]*mlx.Array)
	for k, v := range mlx.Load(path) {
		w[k] = v
	}
	if err := m.LoadWeights(w); err != nil {
		t.Fatal(err)
	}
	weights := mlx.NewScope()
	weights.Attach(mlx.Collect(m)...)
	t.Cleanup(weights.Close)
}

// The fixture is generated by the actual PyTorch GLiNER implementation with
// small random weights. It exercises logarithmic relative positions, both
// LSTM directions, encoder projection, and all span-scoring layers offline.
func TestReferenceForward(t *testing.T) {
	var cfg Config
	readJSON(t, "testdata/config.json", &cfg)
	if err := cfg.validate(); err != nil {
		t.Fatal(err)
	}
	var ref struct {
		IDs             []int32  `json:"ids"`
		WordIndices     []int32  `json:"word_indices"`
		LabelIndices    []int32  `json:"label_indices"`
		Spans           [][2]int `json:"spans"`
		Encoded, Logits []float32
	}
	readJSON(t, "testdata/reference.json", &ref)
	mlxtest.Run(t, func(t *mlxtest.T) {
		mlx.Scoped(func() {
			m := &Model{cfg: cfg}
			loadTestWeights(t, m, "testdata/model.safetensors")
			h, err := m.encode(context.Background(), ref.IDs)
			if err != nil {
				t.Fatal(err)
			}
			closeFloats(t, h.Floats(), ref.Encoded, 2e-5)
			p := &prepared{ids: ref.IDs, wordIndices: ref.WordIndices, labelIndices: ref.LabelIndices, spans: ref.Spans}
			logits, err := m.forward(context.Background(), p)
			if err != nil {
				t.Fatal(err)
			}
			closeFloats(t, logits.Floats(), ref.Logits, 2e-5)
			ctx, cancel := context.WithCancel(context.Background())
			cancel()
			if _, err = m.forward(ctx, p); err != context.Canceled {
				t.Fatalf("cancellation: %v", err)
			}
			delete(m.Weights, "prompt_rep_layer.3.bias")
			if err = m.LoadWeights(m.Weights); err == nil {
				t.Fatal("accepted missing weight")
			}
		})
	})
}

// Run against scripts/export_gliner.py --reference output. The real checkpoint
// is deliberately opt-in so normal tests do not download model weights.
func TestCheckpointParity(t *testing.T) {
	dir := os.Getenv("OLLAMA_GLINER_TEST_MODEL")
	if dir == "" {
		t.Skip("set OLLAMA_GLINER_TEST_MODEL to an export with --reference")
	}
	config, err := os.ReadFile(filepath.Join(dir, "config.json"))
	if err != nil {
		t.Fatal(err)
	}
	tok, err := os.ReadFile(filepath.Join(dir, "tokenizer.json"))
	if err != nil {
		t.Fatal(err)
	}
	m, err := New(config, tok)
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		Input    string
		Labels   []string
		IDs      []int32 `json:"ids"`
		Encoded  []float32
		Entities []api.Entity
	}
	readJSON(t, filepath.Join(dir, "reference.json"), &cases)
	mlxtest.Run(t, func(t *mlxtest.T) {
		loadTestWeights(t, m, filepath.Join(dir, "model.safetensors"))
		for _, c := range cases {
			mlx.Scoped(func() {
				t.Log(c.Input)
				p, err := m.prepare(c.Input, c.Labels)
				if err != nil {
					t.Fatal(err)
				}
				if !slices.Equal(p.ids, c.IDs) {
					t.Fatalf("tokens:\n got %v\nwant %v", p.ids, c.IDs)
				}
				h, err := m.encode(context.Background(), p.ids)
				if err != nil {
					t.Fatal(err)
				}
				closeFloats(t, h.Floats(), c.Encoded, 5e-4)
				out, err := m.Extract(context.Background(), api.ExtractRequest{Input: c.Input, Labels: c.Labels})
				if err != nil {
					t.Fatal(err)
				}
				if len(out.Entities) != len(c.Entities) {
					t.Fatalf("entities: got %+v, expected %+v", out.Entities, c.Entities)
				}
				for i, got := range out.Entities {
					want := c.Entities[i]
					if math.Abs(float64(got.Score-want.Score)) > 1e-4 {
						t.Errorf("score: %v vs %v", got, want)
					}
					got.Score = want.Score
					if got != want {
						t.Errorf("entity: %+v vs %+v", got, want)
					}
				}
			})
		}
	})
}

func TestSplitAndDecode(t *testing.T) {
	if words := splitWords("a\u001cb\u001dc\u001ed\u001fe"); len(words) != 5 {
		t.Fatalf("Python whitespace: %+v", words)
	}
	text := "👋 Élodie met Jean-Luc in São Paulo."
	words := splitWords(text)
	var tokens []string
	for _, w := range words {
		tokens = append(tokens, w.text)
	}
	if !reflect.DeepEqual(tokens, []string{"👋", "Élodie", "met", "Jean-Luc", "in", "São", "Paulo", "."}) {
		t.Fatal(tokens)
	}
	out := decode(text, []string{"person", "city"}, words, [][2]int{{1, 1}, {3, 3}, {5, 5}, {5, 6}}, []float32{.9, .1, .8, .1, .1, .7, .1, .95}, .5)
	want := []api.Entity{{Text: "Élodie", Label: "person", Start: 2, End: 8, Score: .9}, {Text: "Jean-Luc", Label: "person", Start: 13, End: 21, Score: .8}, {Text: "São Paulo", Label: "city", Start: 25, End: 34, Score: .95}}
	if !reflect.DeepEqual(out, want) {
		t.Fatalf("got %+v, want %+v", out, want)
	}
	if out := decode(text, []string{"person"}, words, [][2]int{{1, 1}}, []float32{.5}, .5); len(out) != 0 {
		t.Fatal("threshold is strict")
	}
}
