name: build-sycl-amd64

concurrency:
  # For PRs, later CI runs preempt previous ones. e.g. a force push on a PR
  # cancels running CI jobs and starts all new ones.
  #
  # For non-PR pushes, concurrency.group needs to be unique for every distinct
  # CI run we want to have happen. Use run_id, which in practice means all
  # non-PR CI runs will be allowed to run without preempting each other.
  group: ${{ github.workflow }}-$${{ github.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  push:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:
    inputs:
      cleanup_artifacts:
        description: 'Cleanup old artifacts'
        type: boolean
        default: false
      create_release:
        description: 'Create a new GitHub release'
        type: boolean
        default: false
      release_tag:
        description: 'Release tag (e.g., v1.0.0)'
        type: string
        required: false
      release_name:
        description: 'Release name (optional, defaults to tag)'
        type: string
        required: false

jobs:
  # Optional job to clean up old artifacts
  cleanup-artifacts:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.cleanup_artifacts == 'true'
    steps:
      - name: Delete old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            // Delete artifacts older than 7 days, except those from tagged releases
            const currentTime = new Date();
            const retentionDays = 7;
            const msPerDay = 86400000;
            
            for (const artifact of artifacts.data.artifacts) {
              const createdAt = new Date(artifact.created_at);
              const ageInDays = (currentTime - createdAt) / msPerDay;
              
              // Skip artifacts from tag runs (likely releases)
              if (artifact.workflow_run && artifact.workflow_run.head_branch && artifact.workflow_run.head_branch.startsWith('refs/tags/')) {
                console.log(`Keeping release artifact: ${artifact.name}`);
                continue;
              }
              
              if (ageInDays > retentionDays) {
                console.log(`Deleting artifact: ${artifact.name}, age: ${ageInDays.toFixed(1)} days`);
                await github.rest.actions.deleteArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                });
              }
            }
  
  patches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify patches apply cleanly and do not change files
        run: |
          make -f Makefile.sync clean checkout apply-patches sync
          git diff --compact-summary --exit-code
  
  build-linux:
    runs-on: linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Linux SYCL binaries
        run: |
          . ./scripts/env.sh
          mkdir -p dist
          docker buildx build \
            --output type=local,dest=./dist \
            --platform=linux/amd64 \
            ${OLLAMA_COMMON_BUILD_ARGS} \
            --build-arg FLAVOR=sycl \
            --target archive \
            -f Dockerfile \
            .
          tar c -C ./dist/linux_amd64 --exclude rocm --exclude sycl . | pigz -9vc >./dist/ollama-linux-amd64.tgz
          tar c -C ./dist/ ./lib/ollama/sycl | pigz -9vc >./dist/ollama-linux-amd64-sycl.tgz
        env:
          DOCKER_BUILDKIT: 1

      - name: Upload Linux SYCL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ollama-linux-amd64-${{ github.sha }}
          path: |
            dist/ollama-linux-amd64-sycl.tgz
          if-no-files-found: error
          retention-days: 1

  build-windows:
    runs-on: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          
      - name: Install Inno Setup
        run: |
          choco install -y --no-progress innosetup ninja ccache

      - name: Install AMD64 system dependencies
        run: |
          $ErrorActionPreference = "Stop"
          Start-Process "C:\msys64\usr\bin\pacman.exe" -ArgumentList @("-S", "--noconfirm", "mingw-w64-clang-x86_64-gcc-compat", "mingw-w64-clang-x86_64-clang") -NoNewWindow -Wait
          echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\msys64\clang64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build Windows binaries (AMD64)
        run: |
          powershell -ExecutionPolicy Bypass -File .\scripts\build_windows.ps1
        env:
          ARCH: amd64

      - name: Upload Windows AMD64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ollama-windows-amd64-${{ github.sha }}
          path: |
            dist/ollama-windows-amd64.zip
            dist/ollama-windows-amd64-sycl.zip
            dist/Ollama-*.exe
          if-no-files-found: warn
          retention-days: 1

  release:
    needs: [build-linux, build-windows]
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag || github.ref_name }}
          name: ${{ github.event.inputs.release_name || github.event.inputs.release_tag || github.ref_name }}
          files: |
            artifacts/ollama-linux-amd64-${{ github.sha }}/ollama-linux-amd64-sycl.tgz
            artifacts/ollama-windows-amd64-${{ github.sha }}/ollama-windows-amd64.zip
            artifacts/ollama-windows-amd64-${{ github.sha }}/ollama-windows-amd64-sycl.zip
            artifacts/ollama-windows-amd64-${{ github.sha }}/Ollama-*.exe
          generate_release_notes: true
          draft: false
          prerelease: false 