name: docker-build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ollama:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Verify ollama binary
        run: docker run --rm ollama:${{ github.sha }} --version
